name: Robo Extrator de Cotacao Diario

on:
  schedule:
    - cron: '0 11 * * *' 
  workflow_dispatch: 

permissions:
  contents: write

jobs:
  executar-extracao:
    runs-on: ubuntu-latest # A máquina virtual na nuvem do GitHub (Linux)

    steps:
      - name: 1. Puxar os nossos ficheiros do repositorio
        uses: actions/checkout@v4

      - name: 2. Preparar o ambiente Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13' 

      - name: 3. Instalar o nosso empregado de mesa (Requests)
        run: pip install requests

      - name: 4. Executar o script de extracao!
        run: python "Primeiro projeto SQL/Missao_5.py"

      - name: 5. Guardar a base de dados de volta no GitHub
        run: |
          git config --global user.name 'Robo Extrator'
          git config --global user.email 'robo@github.com'
          git add banco_join.db
          git commit -m "Automação: Nova cotação diária adicionada" || echo "Sem alterações"
          git push  